index page register header and connection forms
WildCodeSchool/2022-09-php-remote-p2-my-tv-tagere pull request #1
Opened 2022-10-26 15:13 UTC by FlorianBetin

2022-10-26 15:14 UTC, MaxenceCodeFR approved these changes

2022-10-26 22:43 UTC, e-riff reviewed
Ya deux élémentd qui m'ont paru bizarre dans les Model, mais pas sur que ce soit handicapant. J'imagine que si c'est push c'est que ça fonctionne, normalement ?

2022-10-26 22:43 UTC, e-riff commented on src/Model/RegisterManager.php
> +        $statement->bindValue(':birthdate', $user['birthdate'], \PDO::PARAM_STR);
Ce n'est pas un param string, si ? Il est initialisé dans la BD comme DATE. Je ne sais pas si ça passe ?

2022-10-26 22:43 UTC, e-riff commented on src/Model/RegisterManager.php
> +        return (int)$this->pdo->lastInsertId();
Le (int) est-il nécessaire ?

2022-10-27 07:33 UTC, Aelex51 approved these changes

2022-10-27 19:01 UTC, jfm-wcs commented on src/Model/RegisterManager.php
> +        return (int)$this->pdo->lastInsertId();
c'est en effet ce qui est donné en exemple sur l'ItemManager...

2022-10-27 19:13 UTC, jfm-wcs requested changes
une petite modification et je pense que ce sera bon.
Ton insertion d'utilisateur fonctionne correctement en BDD 🧐 ?

2022-10-27 19:13 UTC, jfm-wcs commented on src/Controller/RegisterFormController.php
> +
c'est très bien de faire ça, par contre il te manque le constructeur qui va créer l'instance de $registerModel :
```php
public function __construct()
{
    parent::__construct();
    $this->registerModel = new RegisterManager();
}
```
Mais puisque tu le fais dans les méthodes, ça marche aussi 😉

2022-10-27 19:13 UTC, jfm-wcs commented on src/Model/RegisterManager.php
> +        $statement->bindValue(':password', $user['password'], \PDO::PARAM_STR);
aïe 🥶, 
c'est là que ça va pas car on ne doit jamais stocker un mot de passe en clair dans une BDD 😱. Vous avez un atelier là-dessus la semaine prochaine.
Je sais que c'est pour t'entraîner à faire un crud, mais c'est très IMPORTANT.
Je préfère qu'il n'y ait pas de mdp d'enregistrer 🧙‍♂️, il te suffit juste de retirer cette ligne 😉

2022-10-27 19:41 UTC, FlorianBetin commented on src/Controller/RegisterFormController.php
> +
Oui j'ai voulu faire le construct après la vérification que mon test marchait. Puis j'ai oublié avant le push

2022-10-28 07:48 UTC, merged