page seriedetail ajoutee et fonctionelle
WildCodeSchool/2022-09-php-remote-p2-my-tv-tagere pull request #11
Opened 2022-10-30 15:23 UTC by FlorianBetin

Elle est moche, mais ça marche. J'ai pas osé touché au CSS pour pas rentrer en collision avec les autres.

2022-10-30 16:09 UTC, MaxenceCodeFR commented
Je pense que il ne sera pas validée parce que tu as le CI/ build (pull request) qui n'est pas passé . Il te raconte juste que le code est mal indenté en gros ce qu'il fait qu'il ne pourra pas être validé. Tu as 9 erreur dans ce CI Build même si ton code est fonctionnel malheureusement :(

2022-11-02 08:48 UTC, e-riff approved these changes

2022-11-03 07:54 UTC, jfm-wcs requested changes
1 mini correction, sinon ça m'a l'air très bien 👍

2022-11-03 07:54 UTC, jfm-wcs commented on src/View/SeriePage/index.html.twig
> +<br>
petit détail, les `<br>` se mettent à l'intérieur des paragraphes. Si tu as besoin d'espace, utilise plutôt les margin bottom 😉

2022-11-03 07:54 UTC, jfm-wcs commented on src/View/SeriePage/index.html.twig
> +        <p>Nombre de saisons : {{serie.nb_of_seasons}}</p>
idem br

2022-11-03 08:36 UTC, MaxenceCodeFR approved these changes
Je valide

2022-11-03 09:20 UTC, Aelex51 approved these changes

2022-11-03 10:11 UTC, merged