Login fonctionnel et session activée
WildCodeSchool/2022-09-php-remote-p2-my-tv-tagere pull request #18
Opened 2022-11-09 07:46 UTC by FlorianBetin

\\Liste des changements: \\

+ Fichiers twig supprimés: 
=>layout pour la landing et navbar pour le landing. 
=> La landing page extends le layout principal, et utilise la navbar utilisée par Alex. 

+ Fichier twig modifié: 
=> navbar générale: utilise les sessions pour afficher: 
- connexion/enregistrement si pas connecté // 
- // "ajout séries", et "deconnexion" si connecté.
=> Page serie utilise les sessions pour afficher le nom de l'utilisateur

+ Controller pour la connexion avec fonction login. Le manager de la connexion est dans RegisterManager (il va falloir refactorer tout ça quand on aura toutes les pages, fonctions etc...)
=> Impossible d'accéder à la page "serie" sans être connecté.

+DATABASE!!!!!!!!!!!! Ajout du champ 'password' dans la table user! Les password sont "hashé". Pour tous, le mot de passe est mdp.
!!!! Il faudra que vous les ajoutiez dans vos propres DB) ou que vous vous créiez un  compte avec "s'enregistrer" dans la landing page !!!

\\Ce qui manque:\\
+ Ajout de la restriction de connexion quand le Controller de l'ajout d'une série sera là.

2022-11-09 13:25 UTC, jfm-wcs requested changes
tout ceci m'a l'air très bien.
quelques petites améliorations et c'est bon 🤓

2022-11-09 13:25 UTC, jfm-wcs commented on database.sql
>  );
pourquoi ne pas ajouter également le champ `password VARCHAR(255)` ici ?
L'INSERT du dessous ne pourra pas passer sans ça. Et donc on ne pourra pas déployer automatiquement le projet 😉

2022-11-09 13:25 UTC, jfm-wcs commented on src/Controller/ConnexionController.php
> +                    ]);
tu n'es pas obligé de mettre le return ici puisqu'il est également placé ligne 62.

2022-11-09 13:25 UTC, jfm-wcs commented on src/Controller/ConnexionController.php
> +                ]);
idem, le return peut être supprimé

2022-11-09 13:25 UTC, jfm-wcs commented on src/Controller/ConnexionController.php
> +            return $this->twig->render('FormConnect/connect.html.twig');
et enfin, tu peux mettre ici le return complet avec le tableau errors (vide par défaut) :
```php
return $this->twig->render('FormConnect/connect.html.twig',[
                    'errors' => $errors
                ]);
```

2022-11-09 13:25 UTC, jfm-wcs commented on src/Controller/RegisterFormController.php
> +            $user['password'] = password_hash($user['password'], PASSWORD_DEFAULT);
la fonction `password_hash($user['password'], PASSWORD_DEFAULT);` devrait plutôt être mise au niveau du RegisterManager (méthode insert) c'est-à-dire au plus proche de la requête SQL). 🥸

2022-11-09 13:25 UTC, jfm-wcs commented on src/Model/RegisterManager.php
> +        $statement->bindValue(':password', $user['password'], \PDO::PARAM_STR);
ici pour `password_hash($user['password'], PASSWORD_DEFAULT);` 😉

2022-11-09 14:44 UTC, FlorianBetin commented on src/Controller/ConnexionController.php
> +                    ]);
corrigé

2022-11-09 14:44 UTC, FlorianBetin commented on src/Controller/ConnexionController.php
> +            return $this->twig->render('FormConnect/connect.html.twig');
c'est bon

2022-11-09 14:44 UTC, FlorianBetin commented on src/Model/RegisterManager.php
> +        $statement->bindValue(':password', $user['password'], \PDO::PARAM_STR);
fait

2022-11-10 09:59 UTC, jfm-wcs approved these changes

2022-11-10 09:59 UTC, merged