Us3.1
WildCodeSchool/2022-09-php-remote-p2-my-tv-tagere pull request #4
Opened 2022-10-27 08:18 UTC by e-riff

Reflexion future à avoir sur le trop-plein de carrouselle (qui parasitent le scrool) --> Un carroussel + des cards fixe ensuite ?

2022-10-27 08:23 UTC, Aelex51 approved these changes

2022-10-27 08:24 UTC, MaxenceCodeFR approved these changes
ça m'a l'air tout bon , avec la petite avance sur les routes

2022-10-27 08:53 UTC, FlorianBetin approved these changes

2022-10-27 10:25 UTC, MaxenceCodeFR approved these changes
nickel

2022-10-27 14:22 UTC, MaxenceCodeFR approved these changes
Le margin top de -6px va faire mal a JF :D Tampis

2022-10-28 07:05 UTC, e-riff commented
Haha tellement. Même moi il me fait mal au fesse... mais j'arrive pas à
faire autrement.

Le jeu. 27 oct. 2022 à 16:22, Maxence Hattabi ***@***.***> a
écrit :

> ***@***.**** approved this pull request.
>
> Le margin top de -6px va faire mal a JF :D Tampis
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/WildCodeSchool/2022-09-php-remote-p2-my-tv-tagere/pull/4#pullrequestreview-1158386329>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANS2OS7GLK26NZVEUDATF5LWFKF35ANCNFSM6AAAAAARPZCTN4>
> .
> You are receiving this because you authored the thread.Message ID:
> <WildCodeSchool/2022-09-php-remote-p2-my-tv-tagere/pull/4/review/1158386329
> @github.com>
>

2022-10-28 07:26 UTC, jfm-wcs requested changes
juste 1 ligne à retirer dans le fichier sql et c'est tout bon 👍

2022-10-28 07:26 UTC, jfm-wcs commented on Docs/my_tv_tagere.sql
> +CREATE DATABASE my_tv_tagere;
je pense qu'on peut se passer de ce cette ligne vue que c'est géré par migration.php 😉

2022-10-28 07:37 UTC, e-riff commented
C'est fait

Le ven. 28 oct. 2022 à 09:26, Jean-François Morin ***@***.***>
a écrit :

> ***@***.**** requested changes on this pull request.
>
> juste 1 ligne à retirer dans le fichier sql et c'est tout bon 👍
> ------------------------------
>
> In Docs/my_tv_tagere.sql
> <https://github.com/WildCodeSchool/2022-09-php-remote-p2-my-tv-tagere/pull/4#discussion_r1007737989>
> :
>
> > @@ -0,0 +1,43 @@
>
> +CREATE DATABASE my_tv_tagere;
>
>
> je pense qu'on peut se passer de ce cette ligne vue que c'est géré par
> migration.php 😉
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/WildCodeSchool/2022-09-php-remote-p2-my-tv-tagere/pull/4#pullrequestreview-1159584286>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANS2OS4LB6UMYET2CMPLPKDWFN52RANCNFSM6AAAAAARPZCTN4>
> .
> You are receiving this because you authored the thread.Message ID:
> <WildCodeSchool/2022-09-php-remote-p2-my-tv-tagere/pull/4/review/1159584286
> @github.com>
>

2022-10-28 07:51 UTC, jfm-wcs approved these changes

2022-10-28 07:52 UTC, merged